development:
  adapter: postgresql
  encoding: utf8
  database: litestdev
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: litesttest
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: litestprod
  pool: 5
  username: postgres
  password:
